services:
  # Define a container named 'oldman-jenkins' using the latest official Jenkins Image.
  oldman-jenkins:
    image: jenkins/jenkins:lts-jdk17
    ports:
      # Map port 8080 of the host to port 8080 within the container to access Jenkins web interface.
      - "8080:8080"
    volumes:
      # Mount a volume named 'jenkins-vol' to persist Jenkins data across container restarts.
      - jenkins-vol:/var/jenkins_home

volumes:
  # Define a Docker volume named 'jenkins-vol' to persist Jenkins data.
  jenkins-vol:
    driver: local # Specify the volume driver as local
